// The site's HTTP headers from ONE source (Stage 2 PR-1, 2026-09-27): named policies → dist/_headers at build time, and the
// SAME rules resolved per request by the local preview, so what the Director reviews on :4173 answers exactly as Cloudflare
// Pages will (the preview used to apply no policy at all, so a CSP that breaks a page was only seen after the deploy).
// Pure module: no filesystem, no side effects.

/** The Content-Security-Policy directives shared by every page, before a page's own additions. */
const BASE_CSP = {
  'default-src': ["'self'"],
  'script-src': ["'self'", 'https://static.cloudflareinsights.com'],
  // no 'unsafe-inline': every inline style left the pages in PR-1; the build refuses a new one
  'style-src': ["'self'"],
  // no https: — the site's pictures are its own files
  'img-src': ["'self'", 'data:'],
  'font-src': ["'self'"],
  'connect-src': ["'self'", 'https://cloudflareinsights.com', 'https://static.cloudflareinsights.com'],
  'object-src': ["'none'"],
  'base-uri': ["'self'"],
  'form-action': ["'self'"],
  'frame-ancestors': ["'none'"],
  'upgrade-insecure-requests': [],
};

const csp = (directives) => Object.entries(directives).map(([k, v]) => (v.length ? `${k} ${v.join(' ')}` : k)).join('; ');

/** The base policy with a page's additions; a directive the base lacks (frame-src) follows connect-src, as Stage 1 wrote it. */
function withAdded(extra) {
  const out = {};
  for (const [k, v] of Object.entries(BASE_CSP)) {
    out[k] = [...v, ...(extra[k] ?? [])];
    if (k === 'connect-src' && extra['frame-src']) out['frame-src'] = extra['frame-src'];
  }
  return out;
}

/** The /contact page (Stage 1): Turnstile (its script and iframe) and one POST to the contact-inbound function. */
const CONTACT = csp(withAdded({
  'script-src': ['https://challenges.cloudflare.com'],
  'connect-src': ['https://challenges.cloudflare.com', 'https://kfowbpvlejfnntaeljsf.supabase.co'],
  'frame-src': ['https://challenges.cloudflare.com'],
}));

/** The /pay page runs Paddle.js (the overlay checkout for vendor payment links): Paddle's own set, its styles and images
 *  included — the ONE page that keeps 'unsafe-inline' and https: images, because the overlay injects both. */
const PAY_CSP = "default-src 'self'; script-src 'self' https://*.paddle.com; style-src 'self' 'unsafe-inline' https://cdn.paddle.com; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.paddle.com; frame-src https://*.paddle.com; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; upgrade-insecure-requests";

/** Every rule, in the order Pages applies them. `detach` removes a header an earlier matching rule set (`! Name`). */
export const RULES = [
  {
    paths: ['/*'],
    note: 'Cloudflare Pages adds a wildcard CORS header to every response by default; a marketing site has no cross-origin readers, so it is detached (sweep pass 4, D42).',
    detach: ['Access-Control-Allow-Origin'],
    set: {
      'X-Content-Type-Options': 'nosniff',
      'X-Frame-Options': 'DENY',
      'Referrer-Policy': 'strict-origin-when-cross-origin',
      'Permissions-Policy': 'camera=(), microphone=(), geolocation=()',
      'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload',
      'Cross-Origin-Opener-Policy': 'same-origin',
      'Content-Security-Policy': csp(BASE_CSP),
    },
  },
  {
    // BOTH forms: Cloudflare's clean URLs 308 /pay.html → /pay, and the page actually SERVES at /pay (verified live 2026-08-20)
    paths: ['/pay.html', '/pay'],
    note: "The /pay page is the ONE page allowed to run Paddle.js; COOP is detached too — the checkout's 3-D-Secure popups must reach their opener.",
    detach: ['Content-Security-Policy', 'Cross-Origin-Opener-Policy'],
    set: { 'Content-Security-Policy': PAY_CSP },
  },
  {
    paths: ['/contact', '/contact.html', '/he/contact', '/he/contact.html'],
    note: 'The /contact page (Stage 1, 2026-09-26) is the ONE page with the contact form: Turnstile and one cross-origin POST to contact-inbound.',
    detach: ['Content-Security-Policy'],
    set: { 'Content-Security-Policy': CONTACT },
  },
];

/** dist/_headers — one block per path, the note as a comment. */
export function renderHeaders(rules = RULES) {
  const out = ['# GENERATED by scripts/build-site.mjs from scripts/lib/headers.mjs — edit the policies there, never this file.', ''];
  for (const rule of rules) {
    for (const path of rule.paths) {
      out.push(path, `  # ${rule.note}`);
      for (const name of rule.detach) out.push(`  ! ${name}`);
      for (const [name, value] of Object.entries(rule.set)) out.push(`  ${name}: ${value}`);
      out.push('');
    }
  }
  return out.join('\n');
}

/** The headers Pages answers for a request path: every matching rule in order, a detach removing what an earlier one set. */
export function headersFor(pathname, rules = RULES) {
  const result = new Map();
  for (const rule of rules) {
    const hit = rule.paths.some((p) => (p === '/*' ? true : p.endsWith('/*') ? pathname.startsWith(p.slice(0, -1)) : p === pathname));
    if (!hit) continue;
    for (const name of rule.detach) result.delete(name.toLowerCase());
    for (const [name, value] of Object.entries(rule.set)) result.set(name.toLowerCase(), [name, value]);
  }
  return [...result.values()];
}
